name: my_flutter_clean_architecture
description: Architecture proposal.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  dio_logging_interceptor: ^1.0.1
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  flutter_mobx: ^2.0.6+4
  mobx: ^2.1.0
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  dartz: ^0.10.1
  hive: ^2.2.3
  equatable: ^2.0.5
  provider: ^6.0.3  

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  retrofit_generator: ^4.0.1
  mobx_codegen: ^2.0.7+3
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true
